---

- name: Create users ldif file
  template: src=users.ldif.j2 dest={{ openldap_server_app_path }}/users.ldif
  register: users_copy
  when: openldap_enable_user_creation

- name: Add Users
  when: users_copy.changed
  register: command_result
  failed_when: "command_result.rc not in [0,68]"
  shell: ldapadd -c -x -D "{{ openldap_server_rootdn }}" -w {{ openldap_server_rootpw }} -f {{ openldap_server_app_path }}/users.ldif
